#+title: FOI Fewshot
#+author: Lukas Lundmark


* FOI Fewshot
FOI Fewshot is a framework for building and benchmarking common fewshot-classification methods.
Built on top of pytorch and learn2learn.

** Algorithms
Includes implementations of the following fewshot algorithms:

| Algorithm         | Implemented | Tested |
|-------------------+-------------+--------|
| MAML              | yes         | no     |
| ANIL              | yes         | no     |
| Reptile           | yes         | no     |
| ProtoNet          | yes         | no     |
| New Meta Baseline | yes         | no     |
| FRN               | yes         | no     |
| MTL               | no          | no     |

** Training Utilities
Trainer Wrappers inspired by HuggingFace's transformer trainer
Automatic logging of training via tensorboard and to log-files.

** Datasets
All datasets available in l2l.vision can be used with this framework

*** TODO
Compile version of FOI in-house datasets, like e.g. VBS3 generated datasets.

** TODO
1. Add (or maybe just show examples) of how to use outer hyper-parameter optimization with the framework.
2. Add FOI datasets.
3. Extend the Trainers to handle non-image data, instead using texts.
